version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    tty: false
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro